package com.my.blog.website.modal.Vo;

import java.io.Serializable;

/**
 * 外文影视辅表
 * 
 * @author 菠萝大象
 * @version 1.0 2018-06-11
 */
public class Film implements Serializable {
    /**
     * 主键
     */
    private Long id;

    /**
     * post表主键
     */
    private Long cid;

    /**
     * 种子链接
     */
    private String downPath;

    /**
     * 海报
     */
    private String poster;

    /**
     * 其它源码
     */
    private String others;

    /**
     * 大小
     */
    private String size;

    /**
     * 名称
     */
    private String title;

    /**
     * 情况
     */
    private String plot;

    /**
     * 发行年代
     */
    private String year;

    /**
     * 来源
     */
    private String src;

    /**
     * 状态@5:已翻译:1:不用翻译:3:未翻译
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_film
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.id
     *
     * @return the value of t_film.id
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.id
     *
     * @param id the value for t_film.id
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.cid
     *
     * @return the value of t_film.cid
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.cid
     *
     * @param cid the value for t_film.cid
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.down_path
     *
     * @return the value of t_film.down_path
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getDownPath() {
        return downPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.down_path
     *
     * @param downPath the value for t_film.down_path
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setDownPath(String downPath) {
        this.downPath = downPath == null ? null : downPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.poster
     *
     * @return the value of t_film.poster
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.poster
     *
     * @param poster the value for t_film.poster
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setPoster(String poster) {
        this.poster = poster == null ? null : poster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.others
     *
     * @return the value of t_film.others
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.others
     *
     * @param others the value for t_film.others
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.size
     *
     * @return the value of t_film.size
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.size
     *
     * @param size the value for t_film.size
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.title
     *
     * @return the value of t_film.title
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.title
     *
     * @param title the value for t_film.title
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.plot
     *
     * @return the value of t_film.plot
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getPlot() {
        return plot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.plot
     *
     * @param plot the value for t_film.plot
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setPlot(String plot) {
        this.plot = plot == null ? null : plot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.year
     *
     * @return the value of t_film.year
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.year
     *
     * @param year the value for t_film.year
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.src
     *
     * @return the value of t_film.src
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.src
     *
     * @param src the value for t_film.src
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_film.status
     *
     * @return the value of t_film.status
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_film.status
     *
     * @param status the value for t_film.status
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_film
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Film other = (Film) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getDownPath() == null ? other.getDownPath() == null : this.getDownPath().equals(other.getDownPath()))
            && (this.getPoster() == null ? other.getPoster() == null : this.getPoster().equals(other.getPoster()))
            && (this.getOthers() == null ? other.getOthers() == null : this.getOthers().equals(other.getOthers()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getPlot() == null ? other.getPlot() == null : this.getPlot().equals(other.getPlot()))
            && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
            && (this.getSrc() == null ? other.getSrc() == null : this.getSrc().equals(other.getSrc()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_film
     *
     * @mbggenerated Mon Jun 11 09:27:07 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getDownPath() == null) ? 0 : getDownPath().hashCode());
        result = prime * result + ((getPoster() == null) ? 0 : getPoster().hashCode());
        result = prime * result + ((getOthers() == null) ? 0 : getOthers().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getPlot() == null) ? 0 : getPlot().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getSrc() == null) ? 0 : getSrc().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "Film{" +
                "id=" + id +
                ", cid=" + cid +
                ", downPath='" + downPath + '\'' +
                ", poster='" + poster + '\'' +
                ", others='" + others + '\'' +
                ", size='" + size + '\'' +
                ", title='" + title + '\'' +
                ", plot='" + plot + '\'' +
                ", year='" + year + '\'' +
                ", src='" + src + '\'' +
                ", status=" + status +
                '}';
    }
}